@startuml 
 scale max 1080 width
left to right direction 
[<b>styles.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>styles.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>test.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>scienceDirectContentScript.js</b>\n\n Variant:HighlightAndGo] #Grey
[<b>URLUtils.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>scienceDirectContentScript.js</b>\n\n Variant:HighlightAndGo]-->[<b>URLUtils.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>Config.js</b>\n Feature:BuiltIn\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>scienceDirectContentScript.js</b>\n\n Variant:HighlightAndGo]-->[<b>Config.js</b>\n Feature:BuiltIn\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>acmContentScript.js</b>\n\n Variant:HighlightAndGo] #Grey
[<b>URLUtils.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>acmContentScript.js</b>\n\n Variant:HighlightAndGo]-->[<b>URLUtils.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>Config.js</b>\n Feature:BuiltIn\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>acmContentScript.js</b>\n\n Variant:HighlightAndGo]-->[<b>Config.js</b>\n Feature:BuiltIn\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>Events.js</b>\n Feature:UserFilter\n Feature:CodebookUpdate\n Feature:Hierarchy\n Feature:CodebookDelete\n Feature:Manual\n Feature:SidebarNavigation\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>pages.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>pages.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>popup.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>locales.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>locales.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>options.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>version.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>clean.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>clean.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>manifest.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>applyBrowserPrefixesFor.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>manifest.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>applyBrowserPrefixesFor.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>manifest.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>pack.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>pack.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>Config.js</b>\n Feature:BuiltIn\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>fonts.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>fonts.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>background.js</b>\n Feature:GoogleSheetConsumer\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>Popup.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>background.js</b>\n Feature:GoogleSheetConsumer\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>Popup.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>contentScript.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>AnnotationBasedInitializer.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>contentScript.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>AnnotationBasedInitializer.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>ContentScriptManager.js</b>\n Feature:Manual\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>contentScript.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>ContentScriptManager.js</b>\n Feature:Manual\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>scripts.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>scripts.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>build.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>default.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>chromereload.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>chromereload.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>BrowserStorageSearch.js</b>\n\n Variant:HighlightAndGo] #Grey
[<b>BrowserStorageManager.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>BrowserStorageSearch.js</b>\n\n Variant:HighlightAndGo]-->[<b>BrowserStorageManager.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>URLUtils.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>BrowserStorageSearch.js</b>\n\n Variant:HighlightAndGo]-->[<b>URLUtils.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>Alerts.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>BrowserStorageSearch.js</b>\n\n Variant:HighlightAndGo]-->[<b>Alerts.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>Config.js</b>\n Feature:BuiltIn\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>BrowserStorageSearch.js</b>\n\n Variant:HighlightAndGo]-->[<b>Config.js</b>\n Feature:BuiltIn\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>applyBrowserPrefixesFor.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>springerContentScript.js</b>\n\n Variant:HighlightAndGo] #Grey
[<b>URLUtils.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>springerContentScript.js</b>\n\n Variant:HighlightAndGo]-->[<b>URLUtils.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>Config.js</b>\n Feature:BuiltIn\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>springerContentScript.js</b>\n\n Variant:HighlightAndGo]-->[<b>Config.js</b>\n Feature:BuiltIn\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>content.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>content.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
[<b>images.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo] #White
[<b>images.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]-->[<b>args.js</b>\n\n Variant:ConceptAndGo\n Variant:HighlightAndGo]
@enduml